### ISSUE TITLE
'Unknown Error'

### ISSUE THREAD

**Issue by z1haze** [atymic/twitter#184]
Hey, been using this lib for a few months now, and its started giving a random error that just says 'unknown error' here's the stack trace. Please let me know what you think

```
Next ErrorException: [0] Unknown error (View: /var/www/oblivion-networks.com/resources/views/layouts/main.blade.php) (View: /var/www/oblivion-networks.com/resources/views/layouts/main.blade.php) in /var/www/oblivion-networks.com/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php:297
Stack trace:
#0 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/oblivi...', Array)
#2 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/View/View.php(149): Illuminate\View\Engines\CompilerEngine->get('/var/www/oblivi...', Array)
#3 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#4 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#5 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(45): Illuminate\View\View->render()
#6 /var/www/oblivion-networks.com/vendor/symfony/http-foundation/Response.php(201): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /var/www/oblivion-networks.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /var/www/oblivion-networks.com/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}
```

**Comment by thujohn** [comment]
Hi.

What do you have here ? `/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php:297`

**Comment by z1haze** [comment]
That's your file. Its just throwing a generic exception with 'Unknown' as the message.

**Comment by thujohn** [comment]
Yes but the line depends on the version ;)

**Comment by z1haze** [comment]
My mistake, its just the line throwing the generic exception. specifically looks like
```
...
else
			{
				$error_code = $response['code'];
				$error_msg  = ($error_code == 503) ? 'Service Unavailable' : 'Unknown error';
			}

			$this->log('ERROR_CODE : '.$error_code);
			$this->log('ERROR_MSG : '.$error_msg);

			throw new Exception('['.$error_code.'] '.$error_msg, $response['code']);
```

**Comment by thujohn** [comment]
When does this happen?

Which method do you call when this happen?
Can you provide me some code?

**Comment by z1haze** [comment]
I dont have a lot of details on when its happening, it was a bug ticket logged by the client who's website is using it. It just says intermittent. I am caching the feed, maybe thats why its intermittent. I am calling it in a view composer

```
 /**
     * Fetch the latest tweets for the footer
     *
     * @return mixed
     */
    private function getTweets()
    {
        $username = env('TWITTER_USERNAME');
        $number = env('FOOTER_TWITTER_COUNT');

        $tweets = \Cache::get('tweets');

        if ($tweets)
            return $tweets;

        $tweets = Twitter::getUserTimeline(['screen_name' => $username, 'count' => $number, 'format' => 'object']);

        foreach ($tweets as $i => $tweet) {
            $tweets[$i]->text_entitled = $this->addTweetEntityLinks($tweets[$i]);

            $date = date_parse($tweet->created_at);

            if ($date['year'] == date('Y')) {
                $date = date('j F', strtotime($tweet->created_at));
            } else {
                $date = date('j F Y', strtotime($tweet->created_at));
            }
            $tweets[$i]->date_formatted = $date;
        }

        \Cache::put('tweets', $tweets, env('TWITTER_CACHE_LIFETIME'));

        return $tweets;
    }
```

**Comment by thujohn** [comment]
You should try to catch the exception.
When error will happen again you can save the logs in a file or whatever you want.

```php
 try
 {
     $tweets = Twitter::getUserTimeline(['screen_name' => $username, 'count' => $number, 'format' => 'object']);
 }
 catch (\Exception $e)
 {
     dd(Twitter::logs());
 }
```

**Comment by z1haze** [comment]
I'd like to know what is causing the error, and 'unknown' doesnt really help me out much?

**Comment by thujohn** [comment]
I never encountered this error so I can't help you.

Save the logs and you will know more.

**Comment by donguyenha** [comment]
as follow your direction @thujohn 
and i get "ERROR_MSG : Failed connect to api.twitter.com:443; Operation now in progress"

how to fix it :(
> <samp>
        <span class=sf-dump-index>0</span> => "
        <span class=sf-dump-str title="13 characters">METHOD : POST</span>"
        <span class=sf-dump-index>1</span> => "
        <span class=sf-dump-str title="23 characters">QUERY : statuses/update</span>"
        <span class=sf-dump-index>2</span> => "
        <span class=sf-dump-str title="54 characters">URL : https://api.twitter.com/1.1/statuses/update.json</span>"
        <span class=sf-dump-index>3</span> => "
        <span class=sf-dump-str title="52 characters">PARAMETERS : status=Laravel+is+beautiful&amp;format=json</span>"
        <span class=sf-dump-index>4</span> => "
        <span class=sf-dump-str title="17 characters">MULTIPART : false</span>"
        <span class=sf-dump-index>5</span> => "
        <span class=sf-dump-str title="13 characters">FORMAT : json</span>"
        <span class=sf-dump-index>6</span> => "
        <span class=sf-dump-str title="14 characters">ERROR_CODE : 7</span>"
        <span class=sf-dump-index>7</span> => "
        <span class=sf-dump-str title="76 characters">ERROR_MSG : Failed connect to api.twitter.com:443; Operation now in progress</span>"
        <span class=sf-dump-index>8</span> => "
        <span class=sf-dump-str title="14 characters">ERROR_CODE : 0</span>"
        <span class=sf-dump-index>9</span> => "
        <span class=sf-dump-str title="25 characters">ERROR_MSG : Unknown error</span>"
    </samp>]

**Comment by MarouaneSH** [comment]
Hello bro did you solve this problem ? or not ?

**Comment by z1haze** [comment]
nah he didnt do anything about it

**Comment by z1haze** [comment]
i just try/catch

**Comment by MarouaneSH** [comment]
for me it work great on Localhost , but when i upload Laravel appilication on shared Hosting the show me that error

**Comment by MarouaneSH** [comment]
Hello Guys,
i solve this problem , any one facing this problem just change your web hosting , because it being banned from Twiteer ,  i had tested in a free Hosting from Hostinger , when i try in twiiter to add new application with the free hosting domain , they tell me that website is banned , so now when i had used a paied Hosting from Nextwab , it work fine

**Comment by pajoda** [comment]
Started to see this error in the logs today several times.
@MarouaneSH that is not a fix at all. Might have worked for you, because that's one simple reason, why you weren't able to connect to the API.

I'm not using shared hosting, it's a dedicated IP and I'm not banned, because it works fine most of the time. I just see a very few users on my site who receive this error trying to query the API after around 10-11 seconds (information on this comes from the logs and analytics actually, that's why I can even see which Twitter users are trying to be queried -> there are no problems, when I try it with the same users myself).

Ideas:

1. **Something wrong in the well known tmhoauth library.**
(Don't think so)
2. **Problem is based on connecting via SSL.**
I guess this could be possible. The tmhoauth has a section about SSL and response code 0: https://github.com/themattharris/tmhOAuth#a-note-about-security-and-ssl
The cacert.pem is pretty old, so I wget'ed a new version from [haxx.se](https://curl.haxx.se/ca/cacert.pem). Let's see, if the error occours again.
3. **It's just what the error is saying: Can't connect to the Twitter API.**
Unlikely but possible in my opinion. In my case - it happens very unfrequent, that would explain it. Idea 1 and 2 would be strange, because of this.

Any other ideas and people interested in solving it?
