### ISSUE TITLE
Exception in Twitter.php line 297:

### ISSUE THREAD

**Issue by BastinRobin** [atymic/twitter#189]
Whoops, looks like something went wrong.

1/1
Exception in Twitter.php line 297:
[0] Unknown error
in Twitter.php line 297
at Twitter->query('statuses/home_timeline', 'GET', array('count' => '20', 'format' => 'json'), false) in Twitter.php line 316
at Twitter->get('statuses/home_timeline', array('count' => '20', 'format' => 'json')) in StatusTrait.php line 58
at Twitter->getHomeTimeline(array('count' => '20', 'format' => 'json')) in Facade.php line 237
at Facade::__callStatic('getHomeTimeline', array(array('count' => '20', 'format' => 'json'))) in PageController.php line 225
at PageController->get_test(object(Request))
at call_user_func_array(array(object(PageController), 'get_test'), array(object(Request))) in Controller.php line 55
at Controller->callAction('get_test', array(object(Request))) in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(PageController), 'get_test') in Route.php line 189
at Route->runController() in Route.php line 144
at Route->run(object(Request)) in Router.php line 642
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Router.php line 644
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 618
at Router->dispatchToRoute(object(Request)) in Router.php line 596
at Router->dispatch(object(Request)) in Kernel.php line 268
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 150
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
at Kernel->handle(object(Request)) in index.php line 53

**Comment by n-other** [comment]
Also getting this error

[2017-04-05 19:32:56] production.ERROR: Exception: [0] Unknown error in /var/www/production/laravel54/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php:297
Stack trace:
#0 /var/www/production/laravel54/vendor/thujohn/twitter/src/Thujohn/Twitter/Twitter.php(316): Thujohn\Twitter\Twitter->query('direct_messages', 'GET', Array, false)
#1 /var/www/production/laravel54/vendor/thujohn/twitter/src/Thujohn/Twitter/Traits/DirectMessageTrait.php(50): Thujohn\Twitter\Twitter->get('direct_messages', Array)
#2 /var/www/production/laravel54/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Thujohn\Twitter\Twitter->getDmsIn()

**Comment by atymic** [comment]
Closing this due to inactivity. Please let me know if you are still having an issue and i'll reopen.
